import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { S as SectionTitle } from "../../../chunks/SectionTitle.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".section__title{text-transform:uppercase;background:#d8ff4b;margin:0;text-align:center;text-shadow:1px 1px 2px #000;color:#f5f5f5}.content.svelte-7uen69.svelte-7uen69{display:grid;justify-content:center;grid-template-columns:repeat(auto-fit, minmax(150px, 300px));gap:30px;padding:50px 15px}.album.svelte-7uen69.svelte-7uen69{text-decoration:none}.album__border.svelte-7uen69.svelte-7uen69{position:relative}.album__border.svelte-7uen69.svelte-7uen69::before,.album__border.svelte-7uen69.svelte-7uen69::after{content:'';position:absolute;width:100%;height:100%;border:1px solid #c6c6c6;border-radius:5px;box-shadow:inset -2px -2px 5px 1px #ffffff}.album__border.svelte-7uen69.svelte-7uen69::before{z-index:-2;top:3px;left:3px;background:#c1c1c1}.album__border.svelte-7uen69.svelte-7uen69::after{z-index:-3;top:7px;left:7px;background:#b9b9b9}.album__preview-container.svelte-7uen69.svelte-7uen69{position:relative;z-index:-1;height:200px;overflow:hidden;border-radius:5px;margin-bottom:10px;border:1px solid #a9a9a9}.album__preview.svelte-7uen69.svelte-7uen69{object-fit:cover;max-height:200px;filter:blur(1px);transition:all 0.5s}.album.svelte-7uen69:hover .album__preview.svelte-7uen69{transform:scale(1.2);filter:blur(0)}.album__bottom.svelte-7uen69.svelte-7uen69{display:flex;flex-direction:column}.album__name.svelte-7uen69.svelte-7uen69{text-transform:uppercase;text-align:center;font-weight:700;color:#000}.album__length.svelte-7uen69.svelte-7uen69{text-transform:uppercase;text-align:center;font-size:14px;font-weight:700;line-height:1;color:#6d6d6d}@media screen and (min-width: 460px){.section__title{font-size:35px}}@media screen and (max-width: 460px){.section__title{font-size:25px}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-196junf_START -->${$$result.title = `<title>Альбомы Z-park</title>`, ""}<!-- HEAD_svelte-196junf_END -->`, ""} ${validate_component(SectionTitle, "SectionTitle").$$render($$result, { value: "Альбомы из Z-park" }, {}, {})} <div class="content svelte-7uen69" data-svelte-h="svelte-y1csb8"><a class="album svelte-7uen69" href="/photo/birthday"><div class="album__border svelte-7uen69"><div class="album__preview-container svelte-7uen69"><img class="album__preview svelte-7uen69" src="photo1.jpg" alt="photo1"></div></div> <div class="album__bottom svelte-7uen69"><p class="album__name svelte-7uen69">День рождения</p> <p class="album__length svelte-7uen69">10 фото</p></div></a> <a class="album svelte-7uen69" href="/photo/rooms"><div class="album__border svelte-7uen69"><div class="album__preview-container svelte-7uen69"><img class="album__preview svelte-7uen69" src="photo1.jpg" alt="photo1"></div></div> <div class="album__bottom svelte-7uen69"><p class="album__name svelte-7uen69">Комнаты</p> <p class="album__length svelte-7uen69">10 фото</p></div></a> <a class="album svelte-7uen69" href="/photo/menu"><div class="album__border svelte-7uen69"><div class="album__preview-container svelte-7uen69"><img class="album__preview svelte-7uen69" src="photo1.jpg" alt="photo1"></div></div> <div class="album__bottom svelte-7uen69"><p class="album__name svelte-7uen69">Меню</p> <p class="album__length svelte-7uen69">10 фото</p></div></a> <a class="album svelte-7uen69" href="/photo/super-hero"><div class="album__border svelte-7uen69"><div class="album__preview-container svelte-7uen69"><img class="album__preview svelte-7uen69" src="photo1.jpg" alt="photo1"></div></div> <div class="album__bottom svelte-7uen69"><p class="album__name svelte-7uen69">Супер герои</p> <p class="album__length svelte-7uen69">10 фото</p></div></a> <div class="album svelte-7uen69"><div class="album__border svelte-7uen69"><div class="album__preview-container svelte-7uen69"><img class="album__preview svelte-7uen69" src="photo1.jpg" alt="photo1"></div></div> <div class="album__bottom svelte-7uen69"><p class="album__name svelte-7uen69">Кафе</p> <p class="album__length svelte-7uen69">10 фото</p></div></div> <div class="album svelte-7uen69"><div class="album__border svelte-7uen69"><div class="album__preview-container svelte-7uen69"><img class="album__preview svelte-7uen69" src="photo1.jpg" alt="photo1"></div></div> <div class="album__bottom svelte-7uen69"><p class="album__name svelte-7uen69">Атракционы</p> <p class="album__length svelte-7uen69">10 фото</p></div></div> </div>`;
});
export {
  Page as default
};
