import { c as create_ssr_component, f as escape, v as validate_component, e as each, b as add_attribute } from "../../../../chunks/ssr.js";
import { S as SectionTitle } from "../../../../chunks/SectionTitle.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".gallery.svelte-si4qji.svelte-si4qji{position:fixed;top:0;left:0;display:flex;justify-content:center;align-items:center;height:100vh;width:100vw;background-color:#000000cc;z-index:11}.gallery__btn-close.svelte-si4qji.svelte-si4qji{position:absolute;right:20px;top:20px;display:flex;align-items:center;justify-content:center;padding:0;width:50px;height:50px;cursor:pointer;font-size:60px;color:#fff;background:transparent;border:none}.gallery__content.svelte-si4qji.svelte-si4qji{position:relative;width:100%;height:100vh;padding-top:60px;margin:0 100px}.gallery__image.svelte-si4qji.svelte-si4qji{position:absolute;top:50%;left:50%;transform:translate(-50%, -50%);width:auto;height:auto;max-width:100%;max-height:80vh;transition:all .5s}.gallery__controls.svelte-si4qji.svelte-si4qji{position:absolute;top:50%;transform:translateY(-50%);width:100%;display:flex;justify-content:space-between;align-items:center}.gallery__btn-controls.svelte-si4qji.svelte-si4qji{width:100px;height:100px;color:#fff;background:transparent;border:none}.gallery__btn-previous.svelte-si4qji.svelte-si4qji{right:20px}.gallery__btn-next.svelte-si4qji.svelte-si4qji{left:20px}.gallery__controls-svg.svelte-si4qji.svelte-si4qji{width:100%;transition:all 0.2s}.gallery__controls-svg.svelte-si4qji.svelte-si4qji:hover{color:#b9bbff}.gallery__btn-controls.svelte-si4qji:disabled .gallery__controls-svg.svelte-si4qji{color:#505050}@media screen and (max-width: 900px){.gallery.svelte-si4qji.svelte-si4qji{display:flex;flex-direction:column}.gallery__btn-close.svelte-si4qji.svelte-si4qji{width:50px;height:50px;z-index:2;right:10px;top:10px}.gallery__content.svelte-si4qji.svelte-si4qji{width:95%;height:calc(100vh - 200px);margin-bottom:100px;margin-top:70px}.gallery__image.svelte-si4qji.svelte-si4qji{width:auto;height:auto;max-width:100%;max-height:100%}.gallery__controls.svelte-si4qji.svelte-si4qji{justify-content:center;gap:50px;top:auto;bottom:60px;transform:translateY(0)}}.photos__back-container.svelte-si4qji.svelte-si4qji{padding:5px 0}.photos__back-btn.svelte-si4qji.svelte-si4qji{display:inline-block;padding:3px 10px;text-decoration:none;font-size:20px;font-weight:500;border-radius:5px;line-height:1.3;color:#000;background:#aa86ff}.photos__back-img.svelte-si4qji.svelte-si4qji{width:16px;height:16px}.photos.svelte-si4qji.svelte-si4qji{padding-left:clamp(10px, 3vw, 50px);padding-right:clamp(10px, 3vw, 50px)}.photo__content.svelte-si4qji.svelte-si4qji{display:grid;grid-template-columns:repeat(auto-fit, minmax(300px, 300px));justify-content:center;justify-items:center;gap:clamp(15px, 4vw, 50px);padding:20px 0}.photo__img-link.svelte-si4qji.svelte-si4qji{width:300px;height:200px;overflow:hidden;border-radius:5px}.photo__img-link.svelte-si4qji:hover .photo__img.svelte-si4qji{transform:scale(110%)}.photo__img.svelte-si4qji.svelte-si4qji{object-fit:cover;width:100%;height:100%;transition:all 0.4s}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  let images = data.inner;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-fvwe3e_START -->${$$result.title = `<title>Фотографии из альбома ${escape(data.name)}</title>`, ""}<!-- HEAD_svelte-fvwe3e_END -->`, ""} ${validate_component(SectionTitle, "SectionTitle").$$render($$result, { value: data.name }, {}, {})} ${``} <div class="photos svelte-si4qji"><div class="photos__back-container svelte-si4qji" data-svelte-h="svelte-khf0qh"><a href="/photo" class="photos__back-btn svelte-si4qji"><svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="photos__back-img svelte-si4qji" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.854 14.854a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V3.5A2.5 2.5 0 0 1 6.5 1h8a.5.5 0 0 1 0 1h-8A1.5 1.5 0 0 0 5 3.5v9.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4z"></path></svg>
			Назад</a></div> <div class="photo__content svelte-si4qji">${each(images, (image, i) => {
    return `<a class="photo__img-link svelte-si4qji" href="#"><img${add_attribute("src", image, 0)} alt="${"Фото из альбома " + escape(data.name, true)}" class="photo__img svelte-si4qji"> </a>`;
  })}</div> </div>`;
});
export {
  Page as default
};
