import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { S as SectionTitle } from "../../../chunks/SectionTitle.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "p.svelte-p4e24c{margin:0;padding:0;line-height:1.5}.content.svelte-p4e24c{display:flex;gap:20px;flex-wrap:wrap;padding:20px}.left.svelte-p4e24c{flex:55%;width:40vw}.right.svelte-p4e24c{flex:40%}.title.svelte-p4e24c{font-weight:700;font-size:30px;margin-bottom:15px;line-height:1.2}.cards.svelte-p4e24c{display:flex;flex-direction:column;gap:20px}.card.svelte-p4e24c{padding:20px;border:2px solid #bebebe;box-shadow:2px 2px 5px #bebebe;background:#f5f5f5}.card__title.svelte-p4e24c{font-size:26px;font-weight:700;margin-bottom:10px}.card__text.svelte-p4e24c{font-size:18px}.list.svelte-p4e24c{padding:20px;outline:4px dashed #d3d3d3;background:#d3d3d3}.info.svelte-p4e24c{display:flex;flex-direction:column;gap:20px;margin:0 0 20px 0;padding-left:20px}.info__item.svelte-p4e24c{text-transform:uppercase;font-weight:700;font-size:22px;line-height:1.3}.info__text.svelte-p4e24c{text-transform:none;font-weight:400;font-size:18px;padding-top:10px}.btn.svelte-p4e24c{text-transform:uppercase;background:#ffc011;border:none;border-radius:30px;font-size:18px;font-weight:700;color:#f5f5f5;text-shadow:1px 1px 2px #000;padding:10px 30px;box-shadow:1px 1px 2px #868686}@media screen and (max-width: 750px){.left.svelte-p4e24c{min-width:280px}.right.svelte-p4e24c{min-width:270px}.title.svelte-p4e24c{font-size:20px}.card__title.svelte-p4e24c{font-size:18px}.card__text.svelte-p4e24c{font-size:16px}.info__item.svelte-p4e24c{font-size:16px}.info__text.svelte-p4e24c{font-size:16px}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-166wa8v_START -->${$$result.title = `<title>
        Праздинки в Z-park
    </title>`, ""}<!-- HEAD_svelte-166wa8v_END -->`, ""} ${validate_component(SectionTitle, "SectionTitle").$$render($$result, { value: "Праздники в Z-park" }, {}, {})} <div class="content svelte-p4e24c"><div class="left svelte-p4e24c" data-svelte-h="svelte-1p2d1d1"><p class="title svelte-p4e24c">Немного информации</p> <div class="cards svelte-p4e24c"><div class="card svelte-p4e24c"><p class="card__title svelte-p4e24c">Развлечения</p> <p class="card__text svelte-p4e24c">На сайте мы собрали лучшие предложения для самых веселых праздников, но это лишь небольшая часть того, мы можем предложить вам! Узнать про все наши (практически безграничные) возможности можно пообщавшись с главным специалистом по праздникам в самом парке или по телефону +375 XX XXX XX XX.</p></div> <div class="card svelte-p4e24c"><p class="card__title svelte-p4e24c">Никакой арендной платы!</p> <p class="card__text svelte-p4e24c">Мы забронируем для вас одну из комнат для праздников, Вам нужно будет только оплатить входные билеты для маленьких гостей торжества и внести минимальный депозит. Гости старше 18 лет проходят в парк бесплатно! Билеты на мероприятие действуют в течение всего дня - наиграться вдоволь получится у всех!</p></div> <div class="card svelte-p4e24c"><p class="card__title svelte-p4e24c">Угощения</p> <p class="card__text svelte-p4e24c">Наш бренд-шеф создал специальное детское меню для праздников, а взрослые гости смогут выбрать вкусности из основного меню заранее или прямо в процессе торжества!</p></div></div></div> <div class="right svelte-p4e24c"><p class="title svelte-p4e24c" data-svelte-h="svelte-yj9f0p">Можно заказать прмо сейчас!</p> <div class="list svelte-p4e24c"><ol class="info svelte-p4e24c" data-svelte-h="svelte-wm0xz8"><li class="info__item svelte-p4e24c">Кто и когда
                    <p class="info__text svelte-p4e24c">Выберите дату и уточните число гостей</p></li> <li class="info__item svelte-p4e24c">Развлечения и услуги
                    <p class="info__text svelte-p4e24c">Мы подобрали лучших фотографов, аквогримеров и аниматоров, чтобы сделать ваше торжество незабываемым!</p></li> <li class="info__item svelte-p4e24c">Угощения
                    <p class="info__text svelte-p4e24c">В нашем кафе самое необычное детское меню</p></li></ol> <button class="btn svelte-p4e24c" type="button" data-svelte-h="svelte-kiyx1i">Заказать</button></div></div> </div>`;
});
export {
  Page as default
};
