import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { S as SectionTitle } from "../../../chunks/SectionTitle.js";
import { C as CustomBtn } from "../../../chunks/CustomBtn.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".content.svelte-ofosng{display:flex;gap:20px;flex-wrap:wrap;padding:20px}.left.svelte-ofosng{flex:55%;width:40vw}.right.svelte-ofosng{flex:40%}.title.svelte-ofosng{font-weight:700;font-size:30px;margin-bottom:15px;line-height:1.2}.cards.svelte-ofosng{display:flex;flex-direction:column;gap:20px}.card.svelte-ofosng{padding:20px;border:2px solid #bebebe;border-radius:10px;box-shadow:2px 2px 5px #bebebe;background:#f5f5f5}.card__title.svelte-ofosng{font-size:26px;font-weight:700;margin-bottom:10px}.card__text.svelte-ofosng{font-size:18px;line-height:1.5}.list.svelte-ofosng{padding:20px;outline:4px dashed #d3d3d3;border-radius:10px;background:#d3d3d3}.info.svelte-ofosng{display:flex;flex-direction:column;gap:20px;margin:0 0 20px 0}.info__title.svelte-ofosng{margin-bottom:10px;text-transform:uppercase;font-weight:700;font-size:22px;line-height:1.3}.info__text.svelte-ofosng{font-size:18px}@media screen and (max-width: 750px){.left.svelte-ofosng{min-width:280px}.right.svelte-ofosng{min-width:270px}.title.svelte-ofosng{font-size:20px}.card__title.svelte-ofosng{font-size:18px}.card__text.svelte-ofosng{font-size:16px}.info__item.svelte-ofosng{font-size:16px}.info__text.svelte-ofosng{font-size:16px}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-166wa8v_START -->${$$result.title = `<title>
        Праздинки в Z-park
    </title>`, ""}<!-- HEAD_svelte-166wa8v_END -->`, ""} ${validate_component(SectionTitle, "SectionTitle").$$render($$result, { value: "Праздники в Z-park" }, {}, {})} <div class="content svelte-ofosng"><div class="left svelte-ofosng" data-svelte-h="svelte-ddk2sl"><p class="title svelte-ofosng">Немного информации</p> <div class="cards svelte-ofosng"><div class="card svelte-ofosng"><p class="card__title svelte-ofosng">Развлечения</p> <p class="card__text svelte-ofosng"><sapn>На сайте мы собрали лучшие предложения для самых веселых праздников, но это лишь небольшая часть того, мы можем предложить вам!</sapn> <span>Узнать про все наши (практически безграничные) возможности можно пообщавшись с главным специалистом по праздникам в самом парке или по телефону +375 XX XXX XX XX.</span></p></div> <div class="card svelte-ofosng"><p class="card__title svelte-ofosng">Никакой арендной платы!</p> <p class="card__text svelte-ofosng"><span>Мы забронируем для вас одну из комнат для праздников. Вам нужно будет только оплатить входные билеты для маленьких гостей торжества и внести минимальный депозит.</span> <span>Гости старше 18 лет проходят в парк бесплатно!</span> <span>Билеты на мероприятие действуют в течение всего дня - наиграться вдоволь получится у всех!</span></p></div> <div class="card svelte-ofosng"><p class="card__title svelte-ofosng">Угощения</p> <p class="card__text svelte-ofosng"><span>Наш бренд-шеф создал специальное детское меню для праздников, а взрослые гости смогут выбрать вкусности из основного меню заранее или прямо в процессе торжества!</span></p></div></div></div> <div class="right svelte-ofosng"><p class="title svelte-ofosng" data-svelte-h="svelte-fg9jta">Можно заказать прямо сейчас!</p> <div class="list svelte-ofosng"><ol class="info svelte-ofosng" data-svelte-h="svelte-vkui8q"><li class="info__item svelte-ofosng"><p class="info__title svelte-ofosng">Кто и когда</p> <p class="info__text svelte-ofosng">Выберите дату и уточните число гостей</p></li> <li class="info__item svelte-ofosng"><p class="info__title svelte-ofosng">Развлечения и услуги</p> <p class="info__text svelte-ofosng">Мы подобрали лучших фотографов, аквогримеров и аниматоров, чтобы сделать ваше торжество незабываемым!</p></li> <li class="info__item svelte-ofosng"><p class="info__title svelte-ofosng">Угощения</p> <p class="info__text svelte-ofosng">В нашем кафе самое необычное детское меню</p></li></ol> ${validate_component(CustomBtn, "CustomBtn").$$render($$result, { text: "Заказать" }, {}, {})}</div></div> </div>`;
});
export {
  Page as default
};
